cargo-features = ["panic-immediate-abort"]

[package]
name = "Subsystem-for-Arxumbra"
version = "0.0.10"
edition = "2024"

[dependencies]
mimalloc = { git = "https://github.com/purpleprotocol/mimalloc_rust" }
bevy = { git = "https://github.com/bevyengine/bevy", tag = "v0.20.0-rc.2", default-features = false, features = [
    "std",
    "multi_threaded",
    "keyboard",
    "bevy_winit",
    "bevy_render",
    "bevy_input_focus",
    "bevy_core_pipeline",
    "bevy_asset",
    "bevy_image",
    "bevy_sprite",
    "bevy_sprite_render",
    "wayland",
] }